export const SET_UP_FIREBASE = "SET_UP_FIREBASE";

export const START_HOME = 'START_HOME'; // used in redux-saga

export const CLEAR_REDUX_STATE = "CLEAR_REDUX_STATE";

export const SIGN_IN_USER = 'SIGN_IN_USER'; // used in redux-saga
export const SIGN_IN_USER_SUCCESS = 'SIGN_IN_USER_SUCCESS';
export const SIGN_IN_USER_ERROR = 'SIGN_IN_USER_ERROR';

export const SIGN_OUT_USER = 'SIGN_OUT_USER'; // used in redux-saga
export const SIGN_OUT_USER_SUCCESS = 'SIGN_OUT_USER_SUCCESS';
export const SIGN_OUT_USER_ERROR = 'SIGN_OUT_USER_ERROR';

export const SET_UP_USER = 'SET_UP_USER'; // used in redux-saga
export const SET_UP_USER_SUCCESS = 'SET_UP_USER_SUCCESS';
export const SET_UP_USER_ERROR = 'SET_UP_USER_ERROR';

export const CHANGE_PAGE = 'CHANGE_PAGE';

export const PASSWORD_RESET = 'PASSWORD_RESET';
export const SEND_PASSWORD_RESET = 'SEND_PASSWORD_RESET';

export const LOAD_SERVICE_PACKAGES = 'LOAD_SERVICE_PACKAGES';
export const LOAD_SERVICE_PACKAGES_SUCCESS = 'LOAD_SERVICE_PACKAGES_SUCCESS';
export const LOAD_SERVICE_PACKAGES_ERROR = 'LOAD_SERVICE_PACKAGES_ERROR';

export const EDIT_SERVICE_PACKAGE_STATUS = 'EDIT_SERVICE_PACKAGE_STATUS';
export const EDIT_SERVICE_PACKAGE_STATUS_SUCCESS = 'EDIT_SERVICE_PACKAGE_STATUS_SUCCESS';
export const EDIT_SERVICE_PACKAGE_STATUS_ERROR = 'EDIT_SERVICE_PACKAGE_STATUS_ERROR';

export const SET_CURRENT_SERVICE_PACKAGE_UID = 'SET_CURRENT_SERVICE_PACKAGE_UID';

export const LOAD_SERVICE_PACKAGE = 'LOAD_SERVICE_PACKAGE';
export const LOAD_SERVICE_PACKAGE_SUCCESS = 'LOAD_SERVICE_PACKAGE_SUCCESS';
export const LOAD_SERVICE_PACKAGE_ERROR = 'LOAD_SERVICE_PACKAGE_ERROR';
